spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
metro:
  api:
    devid: dummy
    key: dummy
  trainLine: South Morang

slack:
  token: dummy
  postMessage:
    url: https://slack.com/api/chat.postMessage
    channel: dummy

advanceDaysToCheck: 3