spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb?useSSL=false
    username: lichader
    password:
  jpa:
    hibernate:
      ddl-auto: validate
metro:
  api:
    devid: dummy
    key: dummy
  trainLine: South Morang

slack:
  token: dummy
  postMessage:
    url: https://slack.com/api/chat.postMessage
    channel: dummy

advanceDaysToCheck: 3